### ISSUE TITLE
Bug: if last field is empty string you get "null" and odd number of hash elements in split in render function

### ISSUE THREAD

**Issue by marcelser** [mschout/Log-Log4perl-Layout-JSON#2]
Hi,

When that last field in your json configuration is empty string when the pattern is rendered (sub render), you get warning message about "odd number of hash elements" because the split function which splits the fields by separator silently omits the last value if it's empty. You can pass "-1" as additional parameter to the split function, to instruct it not to omit an empty last value.

This behaviour also results in the value beeing "null" instead of an empty string in the json output. Please fix accordingly.

Best regards,

Marc

**Comment by mschout** [comment]
Fixed in v0.53 Thanks.
